// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0OE0X4Z6oglhDYkpwVs6uy1K5ciwQ4QU',
    appId: '1:62969576181:web:79f5bc01530258c86f23bc',
    messagingSenderId: '62969576181',
    projectId: 'scenic-firefly-376309',
    authDomain: 'scenic-firefly-376309.firebaseapp.com',
    storageBucket: 'scenic-firefly-376309.appspot.com',
    measurementId: 'G-TLTV1BKFE8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4TNhNaJtiSWcrCT6UF2MBGL3nrt45mQE',
    appId: '1:62969576181:android:95e362d9f49972fd6f23bc',
    messagingSenderId: '62969576181',
    projectId: 'scenic-firefly-376309',
    storageBucket: 'scenic-firefly-376309.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhuvbPUyTPeR5eT64qSPPWM9Wx7KEXe4g',
    appId: '1:62969576181:ios:7bb8244848b10f036f23bc',
    messagingSenderId: '62969576181',
    projectId: 'scenic-firefly-376309',
    storageBucket: 'scenic-firefly-376309.appspot.com',
    iosClientId: '62969576181-rq0eso2ois2cpu2as3o4q07h1v3kl3n9.apps.googleusercontent.com',
    iosBundleId: 'com.example.complaintManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhuvbPUyTPeR5eT64qSPPWM9Wx7KEXe4g',
    appId: '1:62969576181:ios:7bb8244848b10f036f23bc',
    messagingSenderId: '62969576181',
    projectId: 'scenic-firefly-376309',
    storageBucket: 'scenic-firefly-376309.appspot.com',
    iosClientId: '62969576181-rq0eso2ois2cpu2as3o4q07h1v3kl3n9.apps.googleusercontent.com',
    iosBundleId: 'com.example.complaintManagementSystem',
  );
}
